apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:

      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: python:3.9-slim:latest # Cambia esta línea por la ruta de tu imagen Docker
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: production
        - name: REDIS_HOST
          value: redis # Cambia si tu servicio Redis tiene otro nombre
        - name: REDIS_PORT
          value: "6379" # Cambia si Redis usa un puerto diferente
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  selector:
    app: flask-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-api
spec:
  to:
    kind: Service
    name: flask-api
  port:
    targetPort: 80
  tls:
    termination: edge
